version: '2'
services:
  rtorrent:
    image: rfp-rtorrent
    working_dir: /root
    hostname: rtorrent
    restart: unless-stopped
    ports:
      - "49164:49164"
      - "6881:6881"
    volumes:
      - ./data/rtorrent/downloads:/data/downloads:Z
      - ./data/rtorrent/sessions:/data/sessions:Z
      - ./data/rtorrent/torrents:/data/torrents:Z
    tty: true
  flood:
    image: rfp-flood
    working_dir: /usr/src/flood
    hostname: flood
    restart: unless-stopped
    ports:
     - "3000:3000"
    links:
     - rtorrent
    volumes:
      - ./data/flood:/data/flood:Z
    environment:
      - FLOOD_SECRET=supersecretlikewoah
      - RTORRENT_SCGI_HOST=rtorrent
  plex:
    image: rfp-plex
    hostname: plex
    restart: unless-stopped
    network_mode: host
    environment:
      - TZ=CST
      - PLEX_MEDIA_SERVER_VERSION=1.9.6.4401-53fa66811
    volumes:
      - ./data/plex/config:/data/config:Z
      - ./data/plex/transcode:/data/transcode:Z
      - ./data/plex/media:/data/media:Z
volumes:
    rtorrent:
    flood:
    plex:
