rtorrent:
  image: rfp-rtorrent
  working_dir: /root
  hostname: rtorrent
  restart: unless-stopped
  ports:
    - "49164:49164"
    - "6881:6881"
  volumes:
    - ./data:/data:Z
  tty: true
flood:
  image: rfp-flood
  working_dir: /usr/src/flood
  hostname: flood
  restart: unless-stopped
  ports:
   - "3000:3000"
  links:
   - rtorrent
  volumes:
    - ./data:/data:Z
  environment:
    - FLOOD_SECRET=supersecretlikewoah
    - RTORRENT_SCGI_HOST=rtorrent
plex:
  image: rfp-plex
  hostname: plex
  restart: unless-stopped
  ports:
    - 32400:32400/tcp
    - 3005:3005/tcp
    - 8324:8324/tcp
    - 32469:32469/tcp
    - 1900:1900/udp
    - 32410:32410/udp
    - 32412:32412/udp
    - 32413:32413/udp
    - 32414:32414/udp
  environment:
    - TZ=CST
    - PLEX_MEDIA_SERVER_VERSION=1.9.6.4401-53fa66811
  volumes:
    - ./plex/config:/config:Z
    - ./plex/transcode:/transcode:Z
    - ./data:/data:Z
